name: Reusable nodejs test runner

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    secrets:
      SUPABASE_ACCESS_TOKEN:
        required: true
      SUPABASE_API_KEY:
        required: true
      CONTRACT_OWNER_PRIVATE_KEY:
        required: true
      ALCHEMY_API_KEY:
        required: true
      TEST_WALLET_PRIVATE_KEY:
        required: true
      NASA_API_KEY:
        required: true
      PINATA_API_KEY:
        required: true
      PINATA_API_SECRET:
        required: true
      JWT_SECRET:
        required: true
      JWT_REFRESH_SECRET:
        required: true

env:
  NODE_ENV: development
  PORT: 3000
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
  SUPABASE_PROJECT_ID: "egaldiqizaelreydwdfc"
  CONTRACT_ADDRESS: "0x1BFc8e4631c2710067eEDE979bD9b4Ee44d52B47"
  CONTRACT_OWNER_PRIVATE_KEY: ${{ secrets.CONTRACT_OWNER_PRIVATE_KEY }}
  ALCHEMY_NETWORK: "polygon-mumbai"
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  TEST_WALLET_PRIVATE_KEY: ${{ secrets.TEST_WALLET_PRIVATE_KEY }}
  NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
  PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
  PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

jobs:
  run_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test